# Propietats de configuració de SISTEMES de projectebase.
# La ubicació d'aquest fitxer s'ha de registrar mitjançant la propietat de sistema
# es.caib.projectebase.system.properties (veure apartat 3.5.2 dels estàndards)
# (el fitxer empra la codificació UTF-8)

## BACK START
## BACK END

## FRONT START
# Integració amb LoginIB dins el Front
es.caib.projectebase.front.int.loginib.endpoint=https://se.caib.es/loginibws/rest/v1
es.caib.projectebase.front.int.loginib.usuari=
es.caib.projectebase.front.int.loginib.secret=
## FRONT END

## API INTERNA START
## API INTERNA END

## API EXTERNA START
## API EXTERNA END

## APIFIRMASIMPLE START
## APIFIRMASIMPLE END

## ARXIU START
# Dades de connexió
es.caib.projectebase.int.arxiu.endpoint=https://esbse.caib.es:4430/esb 
es.caib.projectebase.int.arxiu.aplicacioCodi=PROJECTEBASE
es.caib.projectebase.int.arxiu.usuari=
es.caib.projectebase.int.arxiu.secret=
## ARXIU END

## REGISTRE START
# Propietats per connectar amb Registre
es.caib.projectebase.int.registre.endpoint=https://se.caib.es/regweb3/ws/v3/RegWebAsientoRegistral
es.caib.projectebase.int.registre.usuari=
es.caib.projectebase.int.registre.secret=
## REGISTRE END

## NOTIB START
# Propietats per connectar a Notib
es.caib.projectebase.int.notib.endpoint=https://se.caib.es/notib
es.caib.projectebase.int.notib.usuari=
es.caib.projectebase.int.notib.secret=
## NOTIB END

## DIR3CAIB START
# Propietats per connectar amb Dir3Caib
es.caib.projectebase.int.dir3caib.endpoint=https://se.caib.es/dir3caib
es.caib.projectebase.int.dir3caib.usuari=
es.caib.projectebase.int.dir3caib.secret=
## DIR3CAIB END

## DISTRIBUCIO START
# Connexió amb el backofficeintegracio de Distribució
es.caib.projectebase.distribucio.int.distribucio.endpoint=https://se.caib.es/distribucio/ws/backofficeIntegracio
es.caib.projectebase.distribucio.int.distribucio.usuari=
es.caib.projectebase.distribucio.int.distribucio.secret=
## DISTRIBUCIO END

## PINBAL START
# Propietats per connectar amb Distribució per crear anotacions al a bústia
es.caib.projectebase.int.pinbal.endpoint=https://proves.caib.es/pinbal
# Cal que l'usuari tengui el rol PBL_WS
es.caib.projectebase.int.pinbal.usuari=
es.caib.projectebase.int.pinbal.secret=
## PINBAL END

## LOGINIB START
es.caib.projectebase.int.loginib.endpoint=https://se.caib.es/loginibws/rest/v1
es.caib.projectebase.int.loginib.usuari=
es.caib.projectebase.int.loginib.secret=
## LOGINIB END

## WS START
## WS END

# Dialecte de Hibernate
es.caib.projectebase.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
# es.caib.projectebase.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
es.caib.projectebase.hibernate.query.substitutions=true 1, false 0