
package es.caib.projectebase.sistra2.integracio.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BackofficeIntegracio", targetNamespace = "http://www.caib.es/distribucio/ws/backofficeIntegracio")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BackofficeIntegracio {


    /**
     * 
     * @param id
     * @return
     *     returns es.caib.projectebase.sistra2.integracio.api.AnotacioRegistreEntrada
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consulta", targetNamespace = "http://www.caib.es/distribucio/ws/backofficeIntegracio", className = "es.caib.projectebase.sistra2.integracio.api.Consulta")
    @ResponseWrapper(localName = "consultaResponse", targetNamespace = "http://www.caib.es/distribucio/ws/backofficeIntegracio", className = "es.caib.projectebase.sistra2.integracio.api.ConsultaResponse")
    public AnotacioRegistreEntrada consulta(
        @WebParam(name = "id", targetNamespace = "")
        AnotacioRegistreId id);

    /**
     * 
     * @param observacions
     * @param id
     * @param estat
     */
    @WebMethod
    @RequestWrapper(localName = "canviEstat", targetNamespace = "http://www.caib.es/distribucio/ws/backofficeIntegracio", className = "es.caib.projectebase.sistra2.integracio.api.CanviEstat")
    @ResponseWrapper(localName = "canviEstatResponse", targetNamespace = "http://www.caib.es/distribucio/ws/backofficeIntegracio", className = "es.caib.projectebase.sistra2.integracio.api.CanviEstatResponse")
    public void canviEstat(
        @WebParam(name = "id", targetNamespace = "")
        AnotacioRegistreId id,
        @WebParam(name = "estat", targetNamespace = "")
        Estat estat,
        @WebParam(name = "observacions", targetNamespace = "")
        String observacions);

}
