
package es.caib.projectebase.sistra2.integracio.api;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BackofficeIntegracioService", targetNamespace = "http://www.caib.es/distribucio/ws/backofficeIntegracio", wsdlLocation = "/wsdl/backofficeIntegracio.wsdl")
public class BackofficeIntegracioService
    extends Service
{

    private final static URL BACKOFFICEINTEGRACIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException BACKOFFICEINTEGRACIOSERVICE_EXCEPTION;
    private final static QName BACKOFFICEINTEGRACIOSERVICE_QNAME = new QName("http://www.caib.es/distribucio/ws/backofficeIntegracio", "BackofficeIntegracioService");

    static {
        BACKOFFICEINTEGRACIOSERVICE_WSDL_LOCATION = es.caib.projectebase.sistra2.integracio.api.BackofficeIntegracioService.class.getResource("/wsdl/backofficeIntegracio.wsdl");
        WebServiceException e = null;
        if (BACKOFFICEINTEGRACIOSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/backofficeIntegracio.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        BACKOFFICEINTEGRACIOSERVICE_EXCEPTION = e;
    }

    public BackofficeIntegracioService() {
        super(__getWsdlLocation(), BACKOFFICEINTEGRACIOSERVICE_QNAME);
    }

    public BackofficeIntegracioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BACKOFFICEINTEGRACIOSERVICE_QNAME, features);
    }

    public BackofficeIntegracioService(URL wsdlLocation) {
        super(wsdlLocation, BACKOFFICEINTEGRACIOSERVICE_QNAME);
    }

    public BackofficeIntegracioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BACKOFFICEINTEGRACIOSERVICE_QNAME, features);
    }

    public BackofficeIntegracioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BackofficeIntegracioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BackofficeIntegracio
     */
    @WebEndpoint(name = "BackofficeIntegracioServicePort")
    public BackofficeIntegracio getBackofficeIntegracioServicePort() {
        return super.getPort(new QName("http://www.caib.es/distribucio/ws/backofficeIntegracio", "BackofficeIntegracioServicePort"), BackofficeIntegracio.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BackofficeIntegracio
     */
    @WebEndpoint(name = "BackofficeIntegracioServicePort")
    public BackofficeIntegracio getBackofficeIntegracioServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.caib.es/distribucio/ws/backofficeIntegracio", "BackofficeIntegracioServicePort"), BackofficeIntegracio.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BACKOFFICEINTEGRACIOSERVICE_EXCEPTION!= null) {
            throw BACKOFFICEINTEGRACIOSERVICE_EXCEPTION;
        }
        return BACKOFFICEINTEGRACIOSERVICE_WSDL_LOCATION;
    }

}
