
package org.fundaciobit.projectebase.archetype.ws.api.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.12-patch-04
 * Fri Jul 04 08:48:46 CEST 2014
 * Generated source version: 2.2.12-patch-04
 * 
 */

@WebFault(name = "WsValidationErrors", targetNamespace = "http://impl.v1.ws.archetype.projectebase.fundaciobit.org/")
public class WsValidationException extends Exception {
    public static final long serialVersionUID = 20140704084846L;
    
    private org.fundaciobit.projectebase.archetype.ws.api.v1.WsValidationErrors wsValidationErrors;

    public WsValidationException() {
        super();
    }
    
    public WsValidationException(String message) {
        super(message);
    }
    
    public WsValidationException(String message, Throwable cause) {
        super(message, cause);
    }

    public WsValidationException(String message, org.fundaciobit.projectebase.archetype.ws.api.v1.WsValidationErrors wsValidationErrors) {
        super(message);
        this.wsValidationErrors = wsValidationErrors;
    }

    public WsValidationException(String message, org.fundaciobit.projectebase.archetype.ws.api.v1.WsValidationErrors wsValidationErrors, Throwable cause) {
        super(message, cause);
        this.wsValidationErrors = wsValidationErrors;
    }

    public org.fundaciobit.projectebase.archetype.ws.api.v1.WsValidationErrors getFaultInfo() {
        return this.wsValidationErrors;
    }
}
