#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )

package ${package}.ws.api;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-04T14:03:37.185+01:00
 * Generated source version: 3.2.12
 */

@WebFault(name = "WsI18NError", targetNamespace = "http://impl.ws.${rootArtifactId}.caib.es/")
public class WsI18NException extends Exception {

    private ${package}.ws.api.WsI18NError wsI18NError;

    public WsI18NException() {
        super();
    }

    public WsI18NException(String message) {
        super(message);
    }

    public WsI18NException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public WsI18NException(String message, ${package}.ws.api.WsI18NError wsI18NError) {
        super(message);
        this.wsI18NError = wsI18NError;
    }

    public WsI18NException(String message, ${package}.ws.api.WsI18NError wsI18NError, java.lang.Throwable cause) {
        super(message, cause);
        this.wsI18NError = wsI18NError;
    }

    public ${package}.ws.api.WsI18NError getFaultInfo() {
        return this.wsI18NError;
    }
}
