#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )

package ${package}.distribucio.backoffice.api;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Backoffice", targetNamespace = "http://www.caib.es/distribucio/ws/backoffice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Backoffice {


    /**
     * 
     * @param ids
     */
    @WebMethod
    @RequestWrapper(localName = "comunicarAnotacionsPendents", targetNamespace = "http://www.caib.es/distribucio/ws/backoffice", className = "${package}.distribucio.backoffice.api.ComunicarAnotacionsPendents")
    @ResponseWrapper(localName = "comunicarAnotacionsPendentsResponse", targetNamespace = "http://www.caib.es/distribucio/ws/backoffice", className = "${package}.distribucio.backoffice.api.ComunicarAnotacionsPendentsResponse")
    public void comunicarAnotacionsPendents(
        @WebParam(name = "ids", targetNamespace = "")
        List<AnotacioRegistreId> ids);

}
